from setuptools import setup

with open('README.rst', 'r') as r:
    long_description = r.read()

setup(
    name='timeforyoga',
    version='0.0.1',
    description='Play me a yoga video based on how much time I have available.',
    long_description=long_description,
    long_description_content_type='text/x-rst',
    author='Charlotte Padua',
    author_email='charlotte.e.padua@gmail.com',
    url='https://github.com/Charlotte-ER/timeforyoga',
    py_modules=['timeforyoga'],
    package_dir={'':'timeforyoga'},
    classifiers=[
        "Programming Language :: Python :: 3",
        "Development Status :: 3 - Alpha",
        "License :: OSI Approved :: MIT License",
        "Operating System :: Microsoft :: Windows",
        "Natural Language :: English",
    ],
    install_requires=[
        "argparse",
        "requests",
        "webbrowser",
        "googleapiclient",
    ],
    extras_require = {
        'dev': [
            "alabaster==0.7.12",
            "attrs==22.1.0",
            "Babel==2.11.0",
            "cachetools==5.2.0",
            "certifi==2022.12.7",
            "charset-normalizer==2.1.1",
            "colorama==0.4.6",
            "docutils==0.17.1",
            "exceptiongroup==1.0.4",
            "google-api-core==2.11.0",
            "google-api-python-client==2.70.0",
            "google-auth==2.15.0",
            "google-auth-httplib2==0.1.0",
            "googleapis-common-protos==1.57.0",
            "httplib2==0.21.0",
            "idna==3.4",
            "imagesize==1.4.1",
            "importlib-metadata==6.0.0",
            "iniconfig==1.1.1",
            "Jinja2==3.1.2",
            "MarkupSafe==2.1.1",
            "packaging==22.0",
            "pluggy==1.0.0",
            "protobuf==4.21.12",
            "pyasn1==0.4.8",
            "pyasn1-modules==0.2.8",
            "Pygments==2.14.0",
            "pyparsing==3.0.9",
            "pytest==7.2.0",
            "pytz==2022.7",
            "requests==2.28.1",
            "rsa==4.9",
            "six==1.16.0",
            "snowballstemmer==2.2.0",
            "Sphinx==5.3.0",
            "sphinx-rtd-theme==1.1.1",
            "sphinxcontrib-applehelp==1.0.2",
            "sphinxcontrib-devhelp==1.0.2",
            "sphinxcontrib-htmlhelp==2.0.0",
            "sphinxcontrib-jsmath==1.0.1",
            "sphinxcontrib-qthelp==1.0.3",
            "sphinxcontrib-serializinghtml==1.1.5",
            "tomli==2.0.1",
            "uritemplate==4.1.1",
            "urllib3==1.26.13",
            "zipp==3.11.0",
        ]
    },
)